name: Build-Test-Release (dev)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
      - name: Build
        run: |
          if [ -f package.json ]; then
            npm run build || echo "no build step"
          else
            echo "no package.json, skipping build"
          fi
          zip -r build.zip . -x ".git/*"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: build }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run automated tests
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
            npm test
          else
            echo "No tests found (no package.json). Running a smoke check."
            node -e "console.log('smoke ok')"
          fi

  release-dev:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - uses: actions/download-artifact@v4
        with: { name: build }
      - name: Release to Dev
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ vars.BUILD_TAG || format('dev-{0}', github.run_number) }}
          name: ${{ vars.BUILD_TAG || format('dev-{0}', github.run_number) }}
          body: ${{ vars.RELEASE_NOTE || 'Automated dev release after tests' }}
          files: build.zip
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
