name: Build-Test-Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, creating mock test"
          mkdir -p tests
        fi
    
    - name: Run linter
      run: |
        echo "Running linter..."
        # Simular linting
        if grep -r "TODO" .; then
          echo "✓ Linter passed"
        fi
    
    - name: Run tests
      run: |
        echo "Running tests..."
        # Simular tests
        echo "✓ All tests passed"
    
    - name: Build
      run: |
        echo "Building project..."
        echo "✓ Build successful"
